### ISSUE TITLE
Allow view of data generated by a given organization

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#158]
It would be extremely useful to allow a view of all data deposited by a specific `organization` (e.g. `Folding@home`), so that we can present views of all data deposited from a single organization at a time.

**Comment by jchodera** [comment]
Perhaps this can appear under "Contribution > Organizations", where a list of organizations can organize all the data by organization?

**Comment by Lnaden** [comment]
This is something which would take a bit of planning to make sure it's presented correctly. The site organization is not really prone to sorting by a different mechanism, unless its sorted by hand.

Given that, what is the presentation and sorting you see on this? 
* 1 page per org or a monolith page with all orgs and their contribution?
* Under each org, do you want a list of Structures, Models, and Simulations each in their own category?
* For each category, do you want the same sorting where its {Whole Virion/Viral/Host -> Target -> Protein -> Category} or just a flat list?

**Comment by jchodera** [comment]
> Under each org, do you want a list of Structures, Models, and Simulations each in their own category?

This sounds great! Even just linking to the main permalink for each based on the title for each entry would be super useful.

So the concept is: A separate "Organizations" page, with top header listing all the orgs that links to a more detailed list down the page, where for each entry (just listed by title), it's just a link into the main "Structures", "Models", or "Simulations" page.

If this is super complicated or a major effort, it's likely not worth it. But if it's a simple exercise in jinja template loops, it might be a great addition to make it easier to find, for example, all your favorite DESRES datasets.

**Comment by Lnaden** [comment]
> ...each entry (just listed by title), it's just a link into the main...

That simplifies the display of the page significantly!

> If this is super complicated or a major effort,

Its not super complicated, and it *is* just an exercise in Jinja Template loops, but it *is* tedious. It can be done, it will take a few hours though to make sure all the logic is right because Hugo Jinja is not really Jinja-Jinja, mainly because namespace scope within loops is awful in Hugo and working around that makes for complicated code. I think I can throw a couple hours at it this afternoon.
