### ISSUE TITLE
Structure for 6M17.yml has double entries for "protein"

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/covid#18]
**Describe the bug**
As it says on the tin, that file has two top level keys for "protein." I don't know which set is correct.

cc @apayne97 @Binikarki @egoldber

**Comment by Lnaden** [comment]
And it has a double entry for "target" as well.

**Comment by apayne97** [comment]
@Lnaden @hannahbrucemacdonald where should I fix it? in here, in choderalab master, or in my own branch?

**Comment by Lnaden** [comment]
Just tell me here what to change and I can just do it. It will be easier for this 1 thing

Since you all are actively working in the choderalab master branch. The most-correct way (not exactly clean) would be to have your own fork's master be in sync with this one, then make a branch off that on your local fork, make the changes, then make a PR to the master here based on those changes. 

But... it will be much faster to just tell me what to fix here

**Comment by Lnaden** [comment]
See the comments in the linked other issue, this will resolve itself.
