### ISSUE TITLE
Add DOI for RIKEN trajectories

### ISSUE THREAD

**Issue by stain** [MolSSI/covid#239]
I believe the citation for RIKEN trajectories like https://covid.molssi.org/simulations/#riken-cpr-tms-tmd1_toup-trajectory should be:

Takaharu Mori, Jaewoon Jung, Chigusa Kobayashi, Hisham M Dokainish, Suyong Re, Yuji Sugita (2021):  
**Elucidation of interactions regulating conformational stability and dynamics of SARS-CoV-2 S-protein**.  
_Biophysical Journal_ **120**(6)  
https://doi.org/10.1016/j.bpj.2021.01.012

Note that there are several [deposits](https://github.com/MolSSI/covid/search?q=RIKEN) but I have not checked all of them.

**Comment by Lnaden** [comment]
The original entries for this were made back on the first couple weeks of January, a week or so before that publication was made. So its likely the citation didn't properly exist yet. @chig made the original entry and may be able to speak more of it. I can go through the RIKEN entries if I don't hear a response and update the entries as need be.

**Comment by chig** [comment]
I'm sorry for not contacting you for so long.　Yes. The citation for RIKEN trajectories is the paper. I'll update the entry in Github.
