### ISSUE TITLE
Collaborating -> Contributing?

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#56]
It seems like it might be helpful to change "About > Collaborating" to "About > Contributing" to lower the perceptual barrier for others to get involved:
![image](https://user-images.githubusercontent.com/3656088/79390354-65b2fa80-7f24-11ea-8f8b-ad153f907d42.png)
Here, it looks like we have to go through a significant process to decide whether someone is allowed to be a "collaborator" for a monolithic site that is intended to be a community hub.

Instead, it may make sense to list contributors so far (which can be automatically pulled from YAML files, which we could add `contributor:` fields to) and describe several ways in which folks can get involved by
* contributing a PR about a new potential target, structure, model, or molecule (dataset)
* joining a data/contribution review team
* helping with web development
* collaborating in a more substantial way (for orgs like BioExcel/JEDI)

**Comment by Lnaden** [comment]
I want to keep a distinction between a "contributor," which is someone who has added data or helped review data; and a "collaborator," a person or organization who is helping run and maintain the site providing coordination and resources to its operation. Might need to find a better term for it though and put it in its own section. That might just be something add into the about page and rename this one above to contributors

> Instead, it may make sense to list contributors so far (which can be automatically pulled from YAML files, which we could add contributor: fields to)...

Everything else I agree with.

**Comment by jchodera** [comment]
Whoops, I missed that there's now a whole Contributing page!
https://covid.molssi.org/contributing/

**Comment by jchodera** [comment]
Got it, this was my fault for not reading all the new material! Thanks!

**Comment by Lnaden** [comment]
> Whoops, I missed that there's now a whole Contributing page!

Yes, but thats more instructional. We still want a formal "contributors" page, which I'm wanting distinct from "collaborators" (needs a rename due to overlap). So I think this is a good issue to keep open and talk about.

**Comment by Lnaden** [comment]
This has been resolved by recent changes to the layout and organization of the hub
