### ISSUE TITLE
Remove stoplights from structural data

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#68]
We need to remove the stoplights from structural data. They are entirely misleading as to the quality of the structures and their utility for different purposes.

Publication status has no impact on structure quality. If we want to communicate publication status as presence of preprint or published version, we should simply come up with an icon that is displayed for preprint and published that shows up if these are available and absent if they are not.

This is going to cause active harm to the community if we keep these. 

The appropriate annotation data should instead be pulled from the [Coronavirus Structural Task Force](https://github.com/thorn-lab/coronavirus_structural_task_force), but we shouldn't wait for the implementation of that to strip out the stoplight nonsense.

**Comment by Lnaden** [comment]
I'm going to add some additional information about this issue here:

This is in response to the feature added in #61 . I added this comment to that PR after it was closed, but I'll post again here so people don't have to jump back and forth:

> The RYG system is to indicate whether or not a datum has undergone an official, regulated, peer review process at a glance. We're trying to remain as neutral as we can on the mater and are simply accepting data, leaving mechanisms such as issues and project boards for the community and teams to have discussions on the data. If need be, we transfer the discussions to another public facing system if discussing through issues isn't suitable. As the reviews come in and consensus is reached from the community based on both usefulness and quality, we can take advantage of the rating system or some equivalent to indicate what the top data are.
> 
> We are going to be keeping an ear open for community feedback on the subject though, and if people do not like this system, we can work on a replacement.

I'm also going to tag a few people here who have also expressed opinions about this in meetings:
@eriklindahl, Rommie Amaro (I can't find a GitHub presence, will email.), @mojtabah (point of contact in Head-Gordon lab)

**Comment by jchodera** [comment]
@Lnaden: Is there a reason adding icons with links to preprint and/or journal articles does not accomplish the same task while _not_ misleading the reader about the quality of structural data?

**Comment by jchodera** [comment]
For example here is a very simple visual iconography you can use that accomplishes the task of clearly indicating preprint/publication status without being actively harmfully misleading about structure quality (from [here](https://en.wikipedia.org/wiki/Preprint)):
![image](https://user-images.githubusercontent.com/3656088/79787279-98ca0500-82fb-11ea-9f4a-2b91dd385aaa.png)

**Comment by Lnaden** [comment]
Sure, we could do that instead. I can use a few of the Open Access icons instead. Would that be acceptable to the current scheme?

**Comment by jchodera** [comment]
Anything would be better than stoplights right now.
The graphic above is CC-BY, so could also be (re)used if desired (if you have attribution somewhere).

**Comment by Lnaden** [comment]
the new system is in and has 0 ambiguity in my opinion

**Comment by jchodera** [comment]
Huge improvement---thanks!
