### ISSUE TITLE
"New data entries" and "Tracking issue" issue tracker buttons don't open an issue

### ISSUE THREAD

**Issue by jchodera** [MolSSI/covid#71]
**Describe the bug**
The "New data entries" and "Tracking issue" issue tracker buttons take you nowhere useful.

**To Reproduce**
Click on the "New data entries" and "Tracking issue" issue tracker buttons.

**Expected behavior**
These buttons should take you to where they claim to.

**Screenshots**
![image](https://user-images.githubusercontent.com/3656088/79798487-f10a0280-830d-11ea-91ee-981bceb311d0.png)

**Comment by Andrew-AbiMansour** [comment]
Fixed in [PR78](https://github.com/MolSSI/covid/pull/78).
