### ISSUE TITLE
How do data analysis offers get handled?

### ISSUE THREAD

**Issue by CharlieLaughton** [MolSSI/covid#76]
How will this hub take in potential data analysis contributions? We have taken the DESRES 3CLpro trajectories and extracted a small set (34, but adjustable) diverse conformations of the catalytic domain from the 100,000 snapshots - something we think could be useful to those planning docking studies. "Analyses" are not a current data type, so I guess a new schema is needed. In our case the input data (in addition to the DESRES trajectories) is a Jupyter notebook and one PDB format file, the output is the 34 selected structures, again as PDB files.  As a starter:

type: one of [Jupyter notebook, bash script....]
title: (required)
description: (required)
creator: (required)
organization: (optional)
lab: (optional)
institute: (optional)
models: (optional) must point to model in `models` dir
    - modelname_1
    - ...
proteins: (required) Must be a valid protein (see `proteins` dir) 
    - protein 1
    - ...
structures: (optional) must point to structure which could be in `structure` dir
    - structure 1
    - ...
simulations: (optional) must point to simulation which could be in `simulation` dir
    - simulation 1
    - ...
rating: (optional) int on domain [1,5], 5 is better
files: (required) URLs to input and supporting files.
    - file 1
    - ...
references: (optional) List of referfences associated with the programs and methods you want to mention. For publications tied to this exact analysis, use the `publicaton` and `preprint` categories
    - ref1
    - ref2
publication: (optional) URL of the publication which includes THIS analysis
preprint: (optional) URL of the preprint for the publication. Can also be used to note if submitted to a peer reviewed journal by the exact word "Submitted"

**Comment by Andrew-AbiMansour** [comment]
I've made some modifications and additions, and eliminated the `type` keyword for now because I find it difficult to limit the type of analysis. Might get back to that later.  The updated schema so far:

```
title: (required)
description: (required)
creator: (required)
organization: (optional)
lab: (optional)
institute: (optional)
models: (optional) must point to model in models dir
- modelname_1
- ...
proteins: (required) must be a valid protein (see proteins dir)
- protein_1
- ...
molecules: (optional) must be a valid molecule (see molecules dir)
- molecule_1
- ...
structures: (optional) must point to structure which could be in structure dir
- structure_1
- ...
simulations: (optional) must point to simulation which could be in simulation dir
- simulation_1
- ...
rating: (optional) int on domain [1,5], 5 is better
input_files: (required) URLs to input files needed to run the analysis.
- file_1
- ...
analysis_files: (required) URLs to analysis compute files such as python/perl/bash/... script files, a jupyter notebook files, etc.
- file_1
- ...
references: (optional) List of references associated with the programs and methods you want to mention. For publications tied to this exact analysis, use the publicaton and preprint categories
- ref_1
- ref_2
publication: (optional) URL of the publication which includes THIS analysis
preprint: (optional) URL of the preprint for the publication. Can also be used to note if submitted to a peer reviewed journal by the exact word "Submitted"
```

**Comment by CharlieLaughton** [comment]
Looks good. I'm attaching the files that would be needed for the analysis we have done, let's see how they fit this schema.
[DESRES.zip](https://github.com/MolSSI/covid/files/4521823/DESRES.zip)

**Comment by Andrew-AbiMansour** [comment]
I've mapped your analysis metadata to the schema and assumed the pdb/ipynb files can be individually accessed. See below.

```
title: Analysis of DESRES 100 µs MD of 3CLpro, no water or ions
description:
    This notebook analyses the DE Shaw dataset 'DESRES 100 µs MD of 3CLpro, no water or ions (100 µs )' 
    (see https://covid.molssi.org/simulations/#sars-cov-2-main-protease-3clpro-or-nsp5) and extracts a 
    reasonably-sized but diverse subset of structures of the catalytic domain that may be useful for, e.g., 
    docking studies. Structures ('waymarks') are picked sequentially from both A chain and B chain copies 
    of the catalytic domain in each snapshot, if their minimum rmsd from any previously selected structure 
    exceeds a user-defined threshold. These waymarks are then used to produce a Voronoi partitioning of the 
    trajectory. Waymarks defining domains that include more than a set minimum fraction of the trajectory 
    snapshots are then output in PDB format.
creator: Charlie Laughton
institute: School of Pharmacy and Biodiscovery Institute, University of Nottingham, UK.
models:
   - desres_100us_3cl
proteins: 
   - 3CLpro
structures: 
   - 6Y84
simulations: 
   - desres_3clp_100_striped
input_files:
   - https://github.com/MolSSI/covid/files/4521823/system.pdb
   - http://covmme.molssi.org/data/desres/desres_trajs_0/main_protease/DESRES-Trajectory_sarscov2-10880334-no-water-no-ion-glueCA.tar
analysis_files:
   - https://github.com/MolSSI/covid/files/4521823/Extract%structures%for%docking.ipynb
references:
   - D. E. Shaw Research, "Molecular Dynamics Simulations Related to SARS-CoV-2," D. E. Shaw Research 
     Technical Data, 2020. http://www.deshawresearch.com/resources_sarscov2.html
```

Might be a good idea to include software dependencies as well. In your case this might look like this:
```
dependencies:
  - python 3.X
  - mdtraj 1.9.X
  - numpy 1.16.X
  - jupyter lab/notebook
```

**Comment by CharlieLaughton** [comment]
I'm wondering if the term "analysis_files" for the Jupiter notebook (in this case) is the best. Is it obvious what the difference between an "analysis_file" and "input_files" is? Is it obvious that an "analysis_file" is not an output file produced by running the analysis?

**Comment by CharlieLaughton** [comment]
Good point about dependencies. Could be better to use setup.py type syntax maybe, e.g. "mdtraj >= 1.9.3", etc.

**Comment by Andrew-AbiMansour** [comment]
Perhaps "compute_files" is better than "analysis_files" ?

**Comment by Andrew-AbiMansour** [comment]
Yes I agree, setuptools style looks even better for version dependencies.

**Comment by CharlieLaughton** [comment]
I agree with both ideas. The only remaining issue I can think f right now is what happens to the output files the analysis script generates. While it's obviously vital to provide the community with everything they would need to reproduce, or tweak, the analysis, I think it would be good if the default set of outputs (the 34 PDB format files) was also available (especially as, due to the size of the trajectory files that would need to be downloaded, re-running the analysis locally could be a bit of a pain).

**Comment by Andrew-AbiMansour** [comment]
That's a good point. It's possible some might be interested in accessing strictly the output files. Perhaps we can keep the `output_files` an optional keyword that takes in a list of objects:
```
output_files: (optional) URLs to output files generated by the analysis computation.
   - file_1
   - file_2
   - ...
```
One could also zip all the output files and include a single path to avoid long lists, and similarly for many input files.

**Comment by CharlieLaughton** [comment]
Sounds good to me. So are we there? What happens next?

**Comment by Andrew-AbiMansour** [comment]
Can you please upload your input/output/compute files (to a github repo or wherever you wish to host the files) and then fill in the missing info below? I'm going to prepare a README file that defines the schema, and a YAML file that will store your metadata. Will make a PR and see what others think. I'll tag you in the PR so you can stay updated.

```
title: Analysis of DESRES 100 µs MD of 3CLpro, no water or ions
description:
    This notebook analyses the DE Shaw dataset 'DESRES 100 µs MD of 3CLpro, no water or ions (100 µs )' 
    (see https://covid.molssi.org/simulations/#sars-cov-2-main-protease-3clpro-or-nsp5) and extracts a 
    reasonably-sized but diverse subset of structures of the catalytic domain that may be useful for, e.g., 
    docking studies. Structures ('waymarks') are picked sequentially from both A chain and B chain copies 
    of the catalytic domain in each snapshot, if their minimum rmsd from any previously selected structure 
    exceeds a user-defined threshold. These waymarks are then used to produce a Voronoi partitioning of the 
    trajectory. Waymarks defining domains that include more than a set minimum fraction of the trajectory 
    snapshots are then output in PDB format.
creator: Charlie Laughton
institute: School of Pharmacy and Biodiscovery Institute, University of Nottingham, UK.
models:
   - desres_100us_3cl
proteins: 
   - 3CLpro
structures: 
   - 6Y84
simulations: 
   - desres_3clp_100_striped
input_files:
   - https://github.com/MolSSI/covid/files/4521823/system.pdb
   - http://covmme.molssi.org/data/desres/desres_trajs_0/main_protease/DESRES-Trajectory_sarscov2-10880334-no-water-no-ion-glueCA.tar
compute_files:
   - path_to_structures%for%docking.ipynb
output_files:
   - path_to_zip_file
dependencies:
  - python >= ???
  - mdtraj >= ???
  - numpy >= ???
  - jupyter lab/notebook >= ???
references:
   - D. E. Shaw Research, "Molecular Dynamics Simulations Related to SARS-CoV-2," D. E. Shaw Research 
     Technical Data, 2020. http://www.deshawresearch.com/resources_sarscov2.html
```

**Comment by Andrew-AbiMansour** [comment]
[PR91](https://github.com/MolSSI/covid/pull/91)

**Comment by Andrew-AbiMansour** [comment]
Should we try to come up with a general classification (high level) of the common analyses researchers do? It might be useful to think of different classes, might be Physics-based such as thermodynamic analysis (energetics) versus structural (RDF, ...) or temporal (RMSD, ...), or statistical /machine learning (QSAR, ...), etc.

**Comment by CharlieLaughton** [comment]
Here's the file with missing info added:

title: Analysis of DESRES 100 µs MD of 3CLpro, no water or ions
description:
    This notebook analyses the DE Shaw dataset 'DESRES 100 µs MD of 3CLpro, no water or ions (100 µs )'  (see https://covid.molssi.org/simulations/#sars-cov-2-main-protease-3clpro-or-nsp5) and extracts a reasonably-sized but diverse subset of structures of the catalytic domain that may be useful for, e.g., docking studies. Structures ('waymarks') are picked sequentially from both A chain and B chain copies of the catalytic domain in each snapshot, if their minimum rmsd from any previously selected structure exceeds a user-defined threshold. These waymarks are then used to produce a Voronoi partitioning of the trajectory. Waymarks defining domains that include more than a set minimum fraction of the trajectory snapshots are then output in PDB format.
creator: Charlie Laughton
institute: School of Pharmacy and Biodiscovery Institute, University of Nottingham, UK.
models:
   - desres_100us_3cl
proteins: 
   - 3CLpro
structures: 
   - 6Y84
simulations: 
   - desres_3clp_100_striped
input_files:
   - https://bitbucket.org/claughton/covid/src/master/3CLpro/system.pdb
   - http://covmme.molssi.org/data/desres/desres_trajs_0/main_protease/DESRES-Trajectory_sarscov2-10880334-no-water-no-ion-glueCA.tar
compute_files:
   - https://bitbucket.org/claughton/covid/src/master/3CLpro/Select_structures_for_docking.ipynb
output_files:
   - https://bitbucket.org/claughton/covid/src/master/3CLpro/models.tgz
dependencies:
  - python >= 3.4
  - mdtraj >= 1.9.3
  - numpy >= 1.18.2
  - jupyter lab/notebook >= 6.0.3
references:
   - D. E. Shaw Research, "Molecular Dynamics Simulations Related to SARS-CoV-2," D. E. Shaw Research 
     Technical Data, 2020. http://www.deshawresearch.com/resources_sarscov2.html

**Comment by CharlieLaughton** [comment]
Re the high-level classification idea - I might be tempted to go for tags rather than a formal classification - more flexible?

**Comment by Andrew-AbiMansour** [comment]
Thanks Charlie! I like the idea of adding a `tags` keyword instead. This way, you can also add terms specific to covid-19 (e.g. catalytic domain). Can you please fill in the tags you find relevant to your analysis?

**Comment by Andrew-AbiMansour** [comment]
Gentle poke here @CharlieLaughton

**Comment by CharlieLaughton** [comment]
Sorry for going AWOL! suggested tags related to the analytical method: data reduction; diversity analysis

**Comment by Andrew-AbiMansour** [comment]
Thanks for your input Charlie.
